name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.45.1

      - name: Lint
        run: golangci-lint run -v -c .golangci.yml

      - name: Test
        run: make test coverage

      - name: Test Integration
        run: make test-integration coverage
